version: '2'
services:
 db:
  image: mysql:5
  container_name: db
  environment:
    - MYSQL_ROOT_PASSWORD=my-secret-pw
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  ports: 
    - "8081:80"
  links:
    - db
 php:
  image: damp:custom
  container_name: php
  ports:
    - "8080:80"
  links:
    - db
